version: "3.9"

services:
  connector:
    build: .
    container_name: connector
    ports:
      - "10000:10000"
    env_file:
      - .env
    environment:
      - BLOCKCHAIN_RPC_URL=${BLOCKCHAIN_RPC_URL}
      - BLOCKCHAIN_WALLET_PRVT_KEY=${BLOCKCHAIN_WALLET_PRVT_KEY}
      - BLOCKCHAIN_WALLET_ADDR=${BLOCKCHAIN_WALLET_ADDR}
      - ZKSYNC_CHAIN_ID=${BLOCKCHAIN_CHAIN_ID}
      - ZKSYNC_NODE_TYPE=${ZKSYNC_NODE_TYPE}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_AUTH_ANON_KEY}
      - SUPABASE_SERV_KEY=${SUPABASE_AUTH_SERV_KEY}
      - JWT_SECRET=${SUPABASE_AUTH_JWT_SECRET}
      - JWT_ALGORITHM=${SUPABASE_JWT_ALGORITHM}
      - JWT_EXPIRES=${SUPABASE_JWT_EXPIRES}
      - CRED_SERVER_URL=${CRED_SERVER_URL}
      - DEBUG=${DEBUG}
    volumes:
      - .:/connector
