create table
  public.users (
    id bigint generated by default as identity not null,
    first_name text not null default ''::text,
    second_name text not null default ''::text,
    pw_hash text not null default ''::text,
    email text not null default ''::text,
    phone_number text null,
    created_at timestamp with time zone not null default now(),
    last_access_at timestamp with time zone null,
    role text not null default 'user'::text,
    constraint users_pkey primary key (id),
    constraint users_email_key unique (email),
    constraint users_phone_number_key unique (phone_number),
    constraint users_role_key unique (role)
  ) tablespace pg_default;